# Build the operator binary
# ART/doozer replaces this with the rhel-9-golang stream from ocp-build-data at rebase time
FROM registry.redhat.io/openshift/golang-builder:golang-builder-v1.26-rhel9 AS builder

WORKDIR /opt/app-root/src
USER root

COPY . /opt/app-root/src/
# this directory is checked by ecosystem-cert-preflight-checks task in Konflux
COPY LICENSE /licenses/

RUN exportOrFail() { echo $1; if [[ $1 == *= ]]; then echo "Error: empty variable assignment"; exit 1; else export "$1"; fi } && \
    exportOrFail VERSION_PKG="github.com/open-telemetry/opentelemetry-operator/internal/version" && \
    exportOrFail BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') && \
    exportOrFail OPERATOR_VERSION=$(grep -v '\#' versions.txt | grep operator | awk -F= '{print $2}') && \
    exportOrFail OTELCOL_VERSION=$(grep -v '\#' versions.txt | grep opentelemetry-collector | awk -F= '{print $2}') && \
    exportOrFail TARGETALLOCATOR_VERSION=$(grep -v '\#' versions.txt | grep targetallocator | awk -F= '{print $2}') && \
    exportOrFail OPERATOR_OPAMP_BRIDGE_VERSION=$(grep -v '\#' versions.txt | grep operator-opamp-bridge | awk -F= '{print $2}') && \
    exportOrFail AUTO_INSTRUMENTATION_JAVA_VERSION=$(grep -v '\#' versions.txt | grep autoinstrumentation-java | awk -F= '{print $2}') && \
    exportOrFail AUTO_INSTRUMENTATION_NODEJS_VERSION=$(grep -v '\#' versions.txt | grep autoinstrumentation-nodejs | awk -F= '{print $2}') && \
    exportOrFail AUTO_INSTRUMENTATION_PYTHON_VERSION=$(grep -v '\#' versions.txt | grep autoinstrumentation-python | awk -F= '{print $2}') && \
    exportOrFail AUTO_INSTRUMENTATION_DOTNET_VERSION=$(grep -v '\#' versions.txt | grep autoinstrumentation-dotnet | awk -F= '{print $2}') && \
    exportOrFail AUTO_INSTRUMENTATION_GO_VERSION=$(grep -v '\#' versions.txt | grep autoinstrumentation-go | awk -F= '{print $2}') && \
    exportOrFail AUTO_INSTRUMENTATION_APACHE_HTTPD_VERSION=$(grep -v '\#' versions.txt | grep autoinstrumentation-apache-httpd | awk -F= '{print $2}') && \
    exportOrFail AUTO_INSTRUMENTATION_NGINX_VERSION=$(grep -v '\#' versions.txt | grep autoinstrumentation-nginx | awk -F= '{print $2}') && \
    CGO_ENABLED=0 GOFIPS140=certified go build -mod=mod -tags no_openssl -o ./opentelemetry-operator -trimpath -ldflags "-s -w \
              -X ${VERSION_PKG}.version=${OPERATOR_VERSION} \
              -X ${VERSION_PKG}.buildDate=${BUILD_DATE} \
              -X ${VERSION_PKG}.otelCol=${OTELCOL_VERSION} \
              -X ${VERSION_PKG}.targetAllocator=${TARGETALLOCATOR_VERSION} \
              -X ${VERSION_PKG}.operatorOpAMPBridge=${OPERATOR_OPAMP_BRIDGE_VERSION} \
              -X ${VERSION_PKG}.autoInstrumentationJava=${AUTO_INSTRUMENTATION_JAVA_VERSION} \
              -X ${VERSION_PKG}.autoInstrumentationNodeJS=${AUTO_INSTRUMENTATION_NODEJS_VERSION} \
              -X ${VERSION_PKG}.autoInstrumentationPython=${AUTO_INSTRUMENTATION_PYTHON_VERSION} \
              -X ${VERSION_PKG}.autoInstrumentationDotNet=${AUTO_INSTRUMENTATION_DOTNET_VERSION} \
              -X ${VERSION_PKG}.autoInstrumentationGo=${AUTO_INSTRUMENTATION_GO_VERSION} \
              -X ${VERSION_PKG}.autoInstrumentationApacheHttpd=${AUTO_INSTRUMENTATION_APACHE_HTTPD_VERSION} \
              -X ${VERSION_PKG}.autoInstrumentationNginx=${AUTO_INSTRUMENTATION_NGINX_VERSION}"

# ART/doozer replaces this with the base-rhel9 member image from ocp-build-data at rebase time
FROM registry.redhat.io/ubi9/ubi-micro:latest AS target-base

FROM scratch
WORKDIR /
COPY --from=target-base / /

ARG VERSION=0.158.1

RUN mkdir /licenses
COPY LICENSE /licenses/.
COPY --from=builder /opt/app-root/src/opentelemetry-operator /usr/bin/opentelemetry-operator

ENV GODEBUG=fips140=auto
ARG USER_UID=1001
USER ${USER_UID}
ENTRYPOINT ["/usr/bin/opentelemetry-operator"]

LABEL distribution-scope="public" \
      url="https://github.com/open-telemetry/opentelemetry-operator" \
      summary="OpenTelemetry Operator" \
      description="Operator for the OpenTelemetry collector" \
      io.k8s.description="Operator for the OpenTelemetry operator." \
      io.openshift.expose-services="" \
      io.openshift.tags="tracing" \
      io.k8s.display-name="OpenTelemetry Operator" \
      maintainer="support@redhat.com"
